### PR TITLE
[delivers #162601791] Add a page for the user to signin

### PR DESCRIPTION
**Pull request by Nico-Nsereko**
Please check out my code for the user sign in page and comment
@reifred
@Genza999
@ringtho
@v1b3m
@Mastula77
@eryque
@bakersen

### CODE REVIEW

**Comment by bakersen** [comment]
I see It's okay

**Comment by Nico-Nsereko** [comment]
Thanks so much

**Comment by Mastula77** [comment]
It's fine

**Comment by v1b3m** [comment]
Do you have a live version(like gh-pages)?

**Comment by Nico-Nsereko** [comment]
I have it. It's on gh-pages

https://nico-nsereko.github.io/i_Reporter/

**Pull request merged**
